server:
  port: 8080
  contextPath: /CSVUploader
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: local,default
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.MySQLDialect